### ISSUE TITLE
The status of polling

### ISSUE THREAD

**Issue by davydof** [cameronbourke/react-async-poll#4]
I think it really cool if we know about the status of polling, e.g.:
`this.keepPolling` - `true` or `false` in current moment

Thank you :)

@cameronbourke @deepakjois @mxstbr

**Comment by cameronbourke** [comment]
@adavidof Hey! Thanks for the issue.

At the moment I haven't got the bandwidth to dive back into this project. If you think you have a compelling use for it and would like to see it as part of the lib, I'm more than happy to review a PR with you!

**Comment by davydof** [comment]
@cameronbourke 
Ok, I will do the PR in next few days :)
