### ISSUE TITLE
slow down/stop polling when window is not visible

### ISSUE THREAD

**Issue by jason-curtis** [cameronbourke/react-async-poll#5]
To reduce load on the system being polled (and the ones doing the polling), it'd be great to be able to slow down/stop polling while the window is not visible.

This should be feasible using the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) which is now [implemented](http://caniuse.com/#feat=pagevisibility) in modern browsers.

## Suggested changes:

1. `asyncPoll` now takes a third argument: `asyncPoll(intervalDuration, component, hiddenIntervalDuration)` where `hiddenIntervalDuration` is the duration to use when `document.visibilityState` is `hidden`.
2. the tricky part is how to behave when `document.visibilityState` changes. The important edge case here is that if the page is hidden and we have a slow timeout, but then the page becomes visible, we should either poll immediately or wait a little longer and then poll. The airtight way to do this would include storing a `this.lastPolled` timestamp, so that when `document.visibilityState` changes, we can set a timeout with the remaining interval according to the currently correct `intervalDuration`. In some cases (if we switched from a slower interval to a faster interval, and the faster interval says we should have already polled) the new timeout would fire immediately after which we'd settle back in to the regular `setInterval` situation. 

There could also be a simpler approach to this, where whenever `document.visibilityState` changes, we simply poll right then and then carry on with the appropriate interval.

**Comment by cameronbourke** [comment]
@thatneat Hey, thanks so much for this issue! Really appreciate the effort you put into writing this out. Unfortunately I don't have capacity to continue working on this project but I would be more than happy to check PR's and merge them in if you want to continue development!
