### ISSUE TITLE
Stop polling make unable to restart it

### ISSUE THREAD

**Issue by rberthome** [cameronbourke/react-async-poll#7]
When you want to stop polling and call the "stopPolling" method, your cannot restart it. 
The issue comes up because the "interval" property isn't set to undefined (line 29)

**Comment by cameronbourke** [comment]
Thanks @rberthome for the issue! It's a great point. Apologies for the extremely delayed response. I'm not actively maintaining the repo and so I'm going to close this issue due to inactivity of my part. Thanks again!
